FROM python:3.10.15-slim-bookworm

RUN apt-get -y update && apt-get install --no-install-recommends -y \
    postgresql-client libpq-dev gcc libc-dev git

WORKDIR /app

COPY requirements_*.txt .
# The pip-auth library is copied from the openslides-auth-service in the Makefile before the build
# ... in docker-compose.dev.yml the pip-auth is mounted to the container
COPY pip-auth /pip-auth
RUN pip install -r requirements_development.txt

COPY scripts/entrypoint.sh .
COPY scripts/execute-cleanup.sh .
COPY setup.cfg .
COPY scripts/service_env.sh scripts/

RUN chmod 777 -R .

EXPOSE 9006

ENTRYPOINT ["./entrypoint.sh"]
CMD exec flask --app src/mediaserver run --host 0.0.0.0 --port 9006 --debug
